lavender: Drop trust-zone verification
* fix compilation error on A13
error:
m = re.search(r'require\s+version-trustzone\s*=\s*(\S+)', android_info)
      File /home/raiyanbinmohsin/arrow/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/re.py, line 200, in search
    TypeError: cannot use a string pattern on a bytes-like object

Signed-off-by: wHo-EM-i <ehteshammalik18998@gmail.com>